---

- name: Write config
  notify:
    - Restart promtail
  template:
    src: config.j2
    dest: "{{ promtail_config_file }}"
    owner: root
    group: "{{ promtail_system_group }}"
    mode: 0644
