---
- import_tasks: dist_vars.yml

- import_tasks: preflight.yml
  tags:
    - promtail_install
    - promtail
  when:
    - not promtail_install_from_repo

- import_tasks: from_release.yml
  tags:
    - promtail_install
    - promtail
  when: not promtail_install_from_repo

- import_tasks: from_repo.yml
  tags:
    - promtail_install
    - promtail
  when: promtail_install_from_repo

- import_tasks: config.yml
  become: True
  tags:
    - promtail_config
    - promtail

- name: Ensure promtail service is started and enabled
  become: True
  service:
    name: "{{ promtail_service }}"
    state: started
    enabled: True
  tags:
    - promtail_run
    - promtail

- name: Ensure promtail service is started and enabled
  become: True
  service:
    daemon_reload: True
    name: "{{ promtail_service }}"
    state: started
    enabled: True
  when: ansible_service_mgr == "systemd"
  tags:
    - promtail_run
    - promtail
